name: Bug report
description: Relatar um bug
title: "[BUG] Descreva o problema"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Descrição**
        Uma descrição clara e concisa do problema.

        **Passos para Reproduzir**
        Passos para reproduzir o comportamento:
        1. Vá para '...'
        2. Clique em '...'
        3. Role para baixo até '...'
        4. Veja o erro

        **Comportamento Esperado**
        Uma descrição clara e concisa do que você esperava que acontecesse.

        **Capturas de Tela**
        Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

        **Desktop (complete as seguintes informações):**
        - SO: [ex. iOS]
        - Navegador: [ex. chrome, safari]
        - Versão: [ex. 22]

        **Smartphone (complete as seguintes informações):**
        - Dispositivo: [ex. iPhone 6]
        - SO: [ex. iOS 8.1]
        - Navegador: [ex. navegador padrão]
        - Versão: [ex. 22]

        **Contexto Adicional**
        Adicione qualquer outro contexto sobre o problema aqui.
